### ISSUE TITLE
Concentration automation

### ISSUE THREAD

**Issue by Fyorl** [foundryvtt/dnd5e#3028]
### Must Haves
- [x] When casting a spell, create an AE that can act as the origin of any effects applied by that spell.
  - Eagerly created for concentration spells.
  - Lazily created (i.e. if one of the spell's effects is applied to any target) for non-concentration spells that have a duration.
- [x] If the spell requires concentration, the AE should apply the 'concentrating' status.
- [x] Deleting this AE should delete all AEs that were connected to it.
- [x] Create an extra field on the Actor data model for a bonus to concentration saves specifically. Probably in special traits?
- [x] When an Actor takes damage, create a roll request chat message to roll a Constitution (concentration) saving throw with an auto-calculated DC. Send this message to any owner of the Actor.
- [x] Display a warning message in the spell use dialog that reminds a player if their character is already concentrating on something.
- [x] Automatically end concentration if another spell requiring concentration is cast regardless.
- [x] The spell use dialog should allow for an option to not have this instance of the spell require concentration.

### Ideal
- [x] Extend this functionality to any item with the `concentration` property.

### Additional Notes
- Auto-calculating concentration save DC is dependant on us enabling the resistances/immunities/vulnerabilities automation. Not too much work left to do there though. Mostly UI/UX.

**Comment by schultzcole** [comment]
When the origin effect on the casting actor ends, do we also end any effects on other actors that have the origin effect as their origin?

**Comment by krbz999** [comment]
The chat message prompt for saving throws should also have utility buttons for:
- ending concentration easily (perhaps store the uuid of the concentration effect).
- removing templates created from the item on which the actor was concentrating (easy comparison due to `templateDocument.flags.dnd5e.origin`).

> Extend this functionality to any item with the concentration property.

We should make use of `Item5e#requiresConcentration`. There should not be an issue extending this to all item types from the very beginning.

**Comment by Fyorl** [comment]
> When the origin effect on the casting actor ends, do we also end any effects on other actors that have the origin effect as their origin?

Good catch, that is a glaring omission from the requirements. Just to be clear though, we are not intending on handling AE expiration with this epic. Handling manual deletion of AEs should be fine though.

**Comment by JPMeehan** [comment]
For automatically ending concentration when casting another spell with concentration: Making that somehow configurable or its own function would really help with trying to manage the MCDM talent, which is designed around maintaining multiple concentrations. There's also at least one official monster with multiple concentrations, Niv-Mizzet.
