### ISSUE TITLE
Add summoning features to support different summoning types

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3242]
Continuing the work started with #893, this is a list of additional features the summoning system will require to support official summoning spells & features.

## Features Required
- [ ] 1. Summoning based on CR & creature type, rather than explicit UUIDs
- [ ] 2. Summon multiple creatures, increase summoned quantity based on spell level
- [ ] 3. Increase summoned CR based on spell level
- [x] 4. Modify creature type (with choice) (https://github.com/foundryvtt/dnd5e/pull/3372)
- [ ] 5. Modify other stats
- [x] 6. Bonuses to damage formulas (https://github.com/foundryvtt/dnd5e/pull/3244)
- [ ] 7. Profiles restricted by casting level, character, or class level
- [ ] 8. Reference summoned creature's stats in AC & HP bonuses

### SRD/Player's Handbook
- Animate Objects (1, 2)
- Arcane Eye
- Arcane Sword
- Conjure Animals (1, 2)
- Conjure Celestial (1, 3)
- Conjure Elemental (1, 3)
- Conjure Fey (1, 3)
- Conjure Minor Elementals (1, 2)
- Conjure Woodland Beings (1, 2)
- Create Undead (7)
- Dancing Lights (1)
- Find Familiar (4)
- Find Steed (4, 5)
- Giant Insect
- Guardian of Faith
- Mage Hand
- Unseen Servant

### Book of Many Things
- Spirit of Death (6)

### Fizban's Treasury of Dragons
- Summon Draconic Spirit (6)

### Icewind Dale: Rime of the Frostmaiden
- Blade of Disaster

### Tasha's Cauldron of Everything
- Summon Aberration (6)
- Summon Beast (6)
- Summon Celestial (6)
- Summon Construct (6)
- Summon Elemental (6)
- Summon Fey (6)
- Summon Fiend (6)
- Summon Shadowspan (6)
- Summon Undead (6)

### Xanathar's Guide to Everything
- Find Greater Steed (4, 5)
- Healing Spirit (5)
- Infernal Calling* (1, 3)
- Summon Greater Demon* (1, 3)
- Summon Lesser Demons* (1, 2)

* Since these are under the GM control rather than the player, perhaps they don't need direct support or perhaps there is an option in summoning config for who can perform the summoning

### Artificer
- Homunculus Servant
- [Artillerist] Eldritch Cannon (7)
- [Battle Smith] Steel Defender (7)

### Bard
- [College of Creation] Animating Performance

### Cleric
- [Trickery Domain] Channel Divinity: Invoke Duplicity (2, 7)

### Druid
- Wild Companion (see Find Familiar)
- [Circle of Spores] Fungal Infestation
- [Circle of the Shepherd] Spirit Totem
- [Circle of the Shepherd] Mighty Summoner (8)
- [Circle of Wildfire] Summon Wildfire Spirit

### Ranger
- [Beast Master] Ranger's Companion (1, 5)
- [Drakewarden] Drake Companion (7)

### Warlock
- Pact of the Chain (see Find Familiar)

### Wizard
- [Order of Scribes] Manifest Mind
- [School of Necromancy] Undead Thralls (6)

**Comment by szefo09** [comment]
I noticed that Xanathar's Guide to Everything's list doesn't mention Danse Macabre, which could be considered as a pseudo-summoning spell. Is this inteded?
