### ISSUE TITLE
Implement Compendium Browser

### ISSUE THREAD

**Issue by arbron** [foundryvtt/dnd5e#3730]
A number of features in the system require a way to browse content across multiple compendiums.

## Required Features
- [x] Load content quickly from multiple compendiums
- [x] Variety of filters for narrowing down results
  - [x] Document class (e.g. Actor or Item)
  - [x] Types (e.g. Weapon, Equipment, Loot, Class, etc.)
  - [x] Additional filters defined by individual types (e.g. filtering by properties, categories & sub-types, etc.)
- [x] Preset filters that can be programmatically locked in (e.g. clicking the "Add Background" link on the character sheet only shows a list of available backgrounds)
- [x] Search for finding specific item
- [ ] Hiding/disabling specific items in the results (if selecting a class, disable classes that character already has)
- [x] Selecting items and performing an action based on selection

## Nice to Have Features
- [ ] Ability for GMs to control what compendiums are visible in the browser beyond normal permissions
- [ ] Sorting of results by other methods than alphabetical

**Comment by krbz999** [comment]
It would be nice to be able to hide individual items as well.

For example, when a player browses for a class, hiding "GM-only" classes such as those found in the DMG would be good despite those maybe living in a big shared compendium of class items. (User-configurable of course).

Also if the table has decided they are using an unofficial variant of an existing class or subclass, being able to hide the standard one.

**Comment by Zanderaf** [comment]
Yea, hiding stuff would absolutely be great, I remade most of my own stuff in my private compendium, and rarely use the SRD stuff so hiding that would be a real useful thing to be able to do.

**Comment by arbron** [comment]
### Filters by Types
Useful additional filters for specific actor & item types (must be based on indexable data):

#### Class
- Is spellcaster

#### Subclass
- Associated class

#### Race
- Has darkvision

#### Feature
- Feature type & subtype
- Properties

#### Spell
- Level
- School
- Properties
- Spell List (when properly implemented)

#### Physical Items
- Properties
- Rarity
- Requires Attunement
- Category & sub-type

#### NPC
- Creature Size
- Creature Type
- CR (min & max)
- Has certain speed

**Comment by mclemente** [comment]
Would it be interesting to have Casting Time and Action Type as filters for spells?

![image](https://github.com/user-attachments/assets/8f2b7ead-4e86-4207-ac98-3e758529ee1b)

Just add this to `data/item/spell.mjs`:
```js
["activation", {
  label: "DND5E.SpellCastTime",
  type: "set",
  config: {
    choices: ["action", "bonus", "reaction", "minute", "hour"].reduce((acc, key) => {
      acc[key] = CONFIG.DND5E.abilityActivationTypes[key];
      return acc;
    }, {}),
    keyPath: "system.activation.type"
  }
}],
["spellType", {
  label: "DND5E.ItemActionType",
  type: "set",
  config: {
    choices: CONFIG.DND5E.itemActionTypes,
    keyPath: "system.actionType"
  }
}],
```

---

And for NPCs to have a HP range filter?
```js
["hp", {
  label: "DND5E.HitPoints",
  type: "range",
  config: {
    keyPath: "system.attributes.hp",
    min: 0
  },
  createFilter: (filters, value, def) => {
    const min = Number(value.min);
    const max = Number(value.max);
    if ( Number.isFinite(min) ) filters.push({ k: `${def.config.keyPath}.value`, o: "gte", v: min });
    if ( Number.isFinite(max) ) filters.push({ k: `${def.config.keyPath}.max`, o: "lte", v: max });
  }
}],
```

I couldn't get AC to work, because `system.attributes.ac.value` isn't available when reading compendiums.

---

I can bundle these on a PR if you want.
